// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        (unknown)
// source: staffpb/hub.proto

package staffpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindStaffByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FindStaffByIDRequest) Reset() {
	*x = FindStaffByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staffpb_hub_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindStaffByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindStaffByIDRequest) ProtoMessage() {}

func (x *FindStaffByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staffpb_hub_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindStaffByIDRequest.ProtoReflect.Descriptor instead.
func (*FindStaffByIDRequest) Descriptor() ([]byte, []int) {
	return file_staffpb_hub_proto_rawDescGZIP(), []int{0}
}

func (x *FindStaffByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FindStaffByIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Staff *Staff `protobuf:"bytes,1,opt,name=staff,proto3" json:"staff,omitempty"`
}

func (x *FindStaffByIDResponse) Reset() {
	*x = FindStaffByIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staffpb_hub_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindStaffByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindStaffByIDResponse) ProtoMessage() {}

func (x *FindStaffByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staffpb_hub_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindStaffByIDResponse.ProtoReflect.Descriptor instead.
func (*FindStaffByIDResponse) Descriptor() ([]byte, []int) {
	return file_staffpb_hub_proto_rawDescGZIP(), []int{1}
}

func (x *FindStaffByIDResponse) GetStaff() *Staff {
	if x != nil {
		return x.Staff
	}
	return nil
}

type FindStaffByEmailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *FindStaffByEmailRequest) Reset() {
	*x = FindStaffByEmailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staffpb_hub_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindStaffByEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindStaffByEmailRequest) ProtoMessage() {}

func (x *FindStaffByEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staffpb_hub_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindStaffByEmailRequest.ProtoReflect.Descriptor instead.
func (*FindStaffByEmailRequest) Descriptor() ([]byte, []int) {
	return file_staffpb_hub_proto_rawDescGZIP(), []int{2}
}

func (x *FindStaffByEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type FindStaffByEmailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Staff *Staff `protobuf:"bytes,1,opt,name=staff,proto3" json:"staff,omitempty"`
}

func (x *FindStaffByEmailResponse) Reset() {
	*x = FindStaffByEmailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_staffpb_hub_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindStaffByEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindStaffByEmailResponse) ProtoMessage() {}

func (x *FindStaffByEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staffpb_hub_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindStaffByEmailResponse.ProtoReflect.Descriptor instead.
func (*FindStaffByEmailResponse) Descriptor() ([]byte, []int) {
	return file_staffpb_hub_proto_rawDescGZIP(), []int{3}
}

func (x *FindStaffByEmailResponse) GetStaff() *Staff {
	if x != nil {
		return x.Staff
	}
	return nil
}

var File_staffpb_hub_proto protoreflect.FileDescriptor

var file_staffpb_hub_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x74, 0x61, 0x66, 0x66, 0x70, 0x62, 0x2f, 0x68, 0x75, 0x62, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x74, 0x61, 0x66, 0x66, 0x70, 0x62, 0x1a, 0x15, 0x73, 0x74,
	0x61, 0x66, 0x66, 0x70, 0x62, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x26, 0x0a, 0x14, 0x46, 0x69, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x66, 0x66,
	0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3d, 0x0a, 0x15, 0x46,
	0x69, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x66, 0x66, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x66, 0x66, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x53, 0x74,
	0x61, 0x66, 0x66, 0x52, 0x05, 0x73, 0x74, 0x61, 0x66, 0x66, 0x22, 0x2f, 0x0a, 0x17, 0x46, 0x69,
	0x6e, 0x64, 0x53, 0x74, 0x61, 0x66, 0x66, 0x42, 0x79, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x40, 0x0a, 0x18, 0x46,
	0x69, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x66, 0x66, 0x42, 0x79, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x66, 0x66,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x70, 0x62,
	0x2e, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x05, 0x73, 0x74, 0x61, 0x66, 0x66, 0x32, 0xb9, 0x01,
	0x0a, 0x0c, 0x53, 0x74, 0x61, 0x66, 0x66, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4f,
	0x0a, 0x0c, 0x46, 0x69, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x42, 0x79, 0x49, 0x44, 0x12, 0x1d,
	0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x53, 0x74, 0x61,
	0x66, 0x66, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e,
	0x73, 0x74, 0x61, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x66,
	0x66, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x58, 0x0a, 0x0f, 0x46, 0x69, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x42, 0x79, 0x45, 0x6d, 0x61,
	0x69, 0x6c, 0x12, 0x20, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6e,
	0x64, 0x53, 0x74, 0x61, 0x66, 0x66, 0x42, 0x79, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x46,
	0x69, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x66, 0x66, 0x42, 0x79, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x89, 0x01, 0x0a, 0x0b, 0x63, 0x6f,
	0x6d, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x70, 0x62, 0x42, 0x08, 0x48, 0x75, 0x62, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x34, 0x76, 0x6f, 0x63, 0x61, 0x62, 0x2d, 0x62, 0x6f, 0x6f,
	0x73, 0x74, 0x65, 0x72, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2d, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2f, 0x73, 0x74, 0x61, 0x66,
	0x66, 0x70, 0x62, 0x2f, 0x73, 0x74, 0x61, 0x66, 0x66, 0x70, 0x62, 0xa2, 0x02, 0x03, 0x53, 0x58,
	0x58, 0xaa, 0x02, 0x07, 0x53, 0x74, 0x61, 0x66, 0x66, 0x70, 0x62, 0xca, 0x02, 0x07, 0x53, 0x74,
	0x61, 0x66, 0x66, 0x70, 0x62, 0xe2, 0x02, 0x13, 0x53, 0x74, 0x61, 0x66, 0x66, 0x70, 0x62, 0x5c,
	0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x07, 0x53, 0x74,
	0x61, 0x66, 0x66, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_staffpb_hub_proto_rawDescOnce sync.Once
	file_staffpb_hub_proto_rawDescData = file_staffpb_hub_proto_rawDesc
)

func file_staffpb_hub_proto_rawDescGZIP() []byte {
	file_staffpb_hub_proto_rawDescOnce.Do(func() {
		file_staffpb_hub_proto_rawDescData = protoimpl.X.CompressGZIP(file_staffpb_hub_proto_rawDescData)
	})
	return file_staffpb_hub_proto_rawDescData
}

var file_staffpb_hub_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_staffpb_hub_proto_goTypes = []interface{}{
	(*FindStaffByIDRequest)(nil),     // 0: staffpb.FindStaffByIDRequest
	(*FindStaffByIDResponse)(nil),    // 1: staffpb.FindStaffByIDResponse
	(*FindStaffByEmailRequest)(nil),  // 2: staffpb.FindStaffByEmailRequest
	(*FindStaffByEmailResponse)(nil), // 3: staffpb.FindStaffByEmailResponse
	(*Staff)(nil),                    // 4: staffpb.Staff
}
var file_staffpb_hub_proto_depIdxs = []int32{
	4, // 0: staffpb.FindStaffByIDResponse.staff:type_name -> staffpb.Staff
	4, // 1: staffpb.FindStaffByEmailResponse.staff:type_name -> staffpb.Staff
	0, // 2: staffpb.StaffService.FindUserByID:input_type -> staffpb.FindStaffByIDRequest
	2, // 3: staffpb.StaffService.FindUserByEmail:input_type -> staffpb.FindStaffByEmailRequest
	1, // 4: staffpb.StaffService.FindUserByID:output_type -> staffpb.FindStaffByIDResponse
	3, // 5: staffpb.StaffService.FindUserByEmail:output_type -> staffpb.FindStaffByEmailResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_staffpb_hub_proto_init() }
func file_staffpb_hub_proto_init() {
	if File_staffpb_hub_proto != nil {
		return
	}
	file_staffpb_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_staffpb_hub_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindStaffByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staffpb_hub_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindStaffByIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staffpb_hub_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindStaffByEmailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_staffpb_hub_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindStaffByEmailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_staffpb_hub_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_staffpb_hub_proto_goTypes,
		DependencyIndexes: file_staffpb_hub_proto_depIdxs,
		MessageInfos:      file_staffpb_hub_proto_msgTypes,
	}.Build()
	File_staffpb_hub_proto = out.File
	file_staffpb_hub_proto_rawDesc = nil
	file_staffpb_hub_proto_goTypes = nil
	file_staffpb_hub_proto_depIdxs = nil
}
